# create_modules_and_module_videos
"""create_modules_and_module_videos

Revision ID: 73a7294f8f8b
Revises: 0090aa7fde3c
Create Date: 2026-06-18 16:50:57.391404+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a7294f8f8b'
down_revision: Union[str, None] = '0090aa7fde3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_index(op.f('ix_modules_roadmap_id'), 'modules', ['roadmap_id'], unique=False)
    op.create_table('module_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'video_id', name='uq_module_video')
    )
    op.create_index(op.f('ix_module_videos_id'), 'module_videos', ['id'], unique=False)
    op.create_index(op.f('ix_module_videos_module_id'), 'module_videos', ['module_id'], unique=False)
    op.create_index(op.f('ix_module_videos_video_id'), 'module_videos', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_module_videos_video_id'), table_name='module_videos')
    op.drop_index(op.f('ix_module_videos_module_id'), table_name='module_videos')
    op.drop_index(op.f('ix_module_videos_id'), table_name='module_videos')
    op.drop_table('module_videos')
    op.drop_index(op.f('ix_modules_roadmap_id'), table_name='modules')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_table('modules')
    # ### end Alembic commands ###
